cart/urls.py
from django.urls import path

from . views import (
    cart_add, 
    cart_detail, 
    cart_remove
)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    #Django admin
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin-panel-rozgor/', admin.site.urls),

    #Local apps
    
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

orders/urls.py
from django.urls import path
from .views import order_create
 
app_name = 'orders'
 
urlpatterns = [
    path('create/', order_create, name='order_create')
]

shop/urls.py
from shop.models import Category
from django.contrib import admin
from django.urls import path

from .views import (CategoryListView, product_detail, product_list,
                    CategoryDetailView, SearchResultsListView, CategoryListHomeView)

app_name = 'shop'

urlpatterns = [
    path('', CategoryListHomeView.as_view(), name='category_list'),
    path('category/list/', CategoryListView.as_view(), name='categories'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('search/', SearchResultsListView.as_view(), name='search_results'),
]

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label='Количество:', choices=PRODUCT_QUANTITY_CHOICES, coerce=int, 
    widget=forms.Select(
        attrs={'class': 'form-control'}
        ))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib import messages

from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    messages.success(request, 'Удалено')
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}

{% block content %}
    <main>
        <section class="korzina_div">
            <div class="container">
                <h4>Hozir savatchada :</h4>
                <div class="kor_div_wrap">


                    <!-- Это надо копировать от сюда -->
                    {% for item in cart %}
                    {% with product=item.product  %}
                    <div class="kor_div col-lg-6">
                        <div class="kor_img">
                            <img src="{% if product.image %} {{ product.image }} {% endif %}" alt="">
                        </div>
                        <div class="kor_content">
                            <h2>{{product.name}}</h2>
                            <!-- <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {% csrf_token %}
                                <span style="display:inline-block">    
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Изменить">
                                </span>
                            </form> -->
                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                {% csrf_token %}
                                <label for="">Ko'pligi : </label>
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                {{item.measurement}}
                                <input type="submit" value="Tahrirlash">
                            </form>
                            <div class="button_del">
                                <a class="del" href="{% url "cart:cart_remove" product.id %}">O'chirish</a>
                                <a class="see" href="{{ product.get_absolute_url }}">Qarang</a>
                            </div>
                            <h4>Bitta buyum narxi : <span class="one_price">{{item.price}}</span></h4>
                            <h4>Narx : <span class="price">{{item.total_price}}</span></h4>
                        </div>
                    </div>
                    {% endwith %}
                    {% endfor %}
                    <!-- До Сюда -->
                    


                </div>
                <div class="total">
                    <h2>Umumiy qiymati : <span class="total_price">{{ cart.get_total_price }}</span></h2>
                </div>

                <div class="zakaz">
                    <a class="continue" href="{% url "shop:category_list" %}">Xarid qilishni davom eting</a>
                    <a class="arrange" href="{% url "orders:order_create" %}">Tekshirib ko'rmoq</a>
                </div>
            </div>
        </section>
    </main>
{% endblock content %}
    