cart/urls.py
from django.urls import path

from . views import (
    cart_add, 
    cart_detail, 
    cart_remove
)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    #Django admin
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin-panel-rozgor/', admin.site.urls),

    #Local apps
    
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

shop/urls.py
from shop.models import Category
from django.contrib import admin
from django.urls import path

from .views import (CategoryListView, product_detail, product_list,
                    CategoryDetailView, SearchResultsListView, CategoryListHomeView)

app_name = 'shop'

urlpatterns = [
    path('', CategoryListHomeView.as_view(), name='category_list'),
    path('category/list/', CategoryListView.as_view(), name='categories'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('search/', SearchResultsListView.as_view(), name='search_results'),
]

shop/models.py
import os
from django.db import models
from django.db.models import indexes
from django.urls import reverse
import datetime
from django.utils import timezone


# Create your models here.

def get_upload_path(instance, filename):
    #  задаем название файла названием slug`а продукта
    filename = instance.slug + '.' + filename.split('.')[1]
    return os.path.join('images/', filename)


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cover = models.CharField(max_length=500, null=True)

    class Meta:
        indexes = [
            models.Index(fields=['slug'], name='slug_index'),
        ]
        ordering = ('name',)
        verbose_name = 'Categoriya'
        verbose_name_plural = 'Categoriyalar'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:category_detail', args=[self.slug])


class Measurement(models.Model):
    name = models.CharField(max_length=50, db_index=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Birlik'
        verbose_name_plural = 'Birlik'


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products',
        on_delete=models.CASCADE
    )
    measurement = models.ForeignKey(Measurement, related_name='measurement', null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.CharField(max_length=500, null=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Mahsulot'
        verbose_name_plural = 'Mahsulotlar'
        indexes = [
            models.Index(fields=['id'], name='id_index'),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def was_added_recently(self):
        return self.created_at >= (timezone.now() - datetime.timedelta(days=7))


class Banner:
    name = models.CharField(max_length=50)
    photo = models.ImageField(upload_to=get_upload_path)

    class Meta:
        verbose_name = 'Баннер'
        verbose_name_plural = 'Баннеры'

    def __str__(self):
        return self.name

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label='Количество:', choices=PRODUCT_QUANTITY_CHOICES, coerce=int, 
    widget=forms.Select(
        attrs={'class': 'form-control'}
        ))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/views.py
from django.db.models import query
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from .models import Category, Product
from cart.forms import CartAddProductForm

from django.views.generic import (
    ListView,
    DetailView
)
'''
class ProductListView(ListView):
    template_name = 'shop/product/list.html'
    queryset = Product.objects.all()
    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context
'''


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)


class CategoryListHomeView(ListView):
    model = Category
    context_object_name = 'category_list'
    template_name = 'shop/product/list.html'


class CategoryListView(ListView):
    model = Category
    context_object_name = 'category_list'
    template_name = 'shop/product/category_list.html'


class CategoryDetailView(DetailView):
    model = Category
    context_object_name = 'category'
    template_name = 'shop/product/category_detail.html'


class SearchResultsListView(ListView):
    model = Product
    context_object_name = 'product_list'
    template_name = 'shop/product/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Product.objects.filter(
            Q(name__icontains=query) | Q(description__icontains=query)
        )

shop/templates/shop/product/category_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ category.name }}{% endblock title %}

{% block content %}
<main>


    <section class="category_div">
        <h1>{{category.name}}:</h1>
        <div class="container-fluid">
            {% for product in category.products.all %}
            <div class="category_item">
                <img src="{{ product.image }}" alt="">
                <p>{{product.name}}</p>
                <h4>{{product.price}}so'm</h4>
                <div class="item_buttons">
                    <a href="{{ product.get_absolute_url }}">Batafsil</a>

                </div>
                <div class="dropdown_div">
                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                        {% csrf_token %}
                        {{ cart_product_form }}
                        <select name="quantity" class="form-control" id="id_quantity">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                        <h5>{{product.measurement}}</h5>
                        <input type="hidden" name="update" value="False" id="id_update">
                        <input type="submit" value="xaridga qo'shish">
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>

</main>
{% endblock content %}

shop/templates/shop/product/detail.html
{% extends 'base.html' %}

{% block content %}
<!-- <div class="container">
        <div class="row" style="margin-bottom: 5%;">
            <div class="col-sm-4">
                    <img src="{{ product.image.url }}" alt="" style="width: 100%">
            </div>
            <div class="col-sm-8">
                <h1>{{ product.title }}</h1>
                <p>{{ product.description | safe }}</p>
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                        {% csrf_token %}
                        {{ cart_product_form }}
                        <input type="submit" value="add to cart" class="btn btn-outline-danger">
                    </form>
                <button type="button" value="Previous Page" class="btn btn-outline-warning" onClick="window.history.back();return false;">
                    Назад
                </button>
            </div>
        </div>
        
    <div class="btn-group" role="group" aria-label="...">
        {% for category in category_list %}
            <a class="btn btn-outline-secondary" href="{{ category.get_absolute_url }}" role="button" style="margin-left: 10px;">
                {{ category.name }}
            </a>
        {% endfor %}
    </div>
</div> -->
<main>
    

    
    <section class="tovar">
        <div class="container">
            <div class="tovar_left col-lg-6">
                <div class="tovar_img">
                    <img src="{{ product.image }}" alt="">
                </div>
            </div>
            <div class="tovar_right col-lg-6">
                <h1>{{ product.name }}</h1>
                <h2 class="price">{{product.price}}<span>so'm</span></h2>
                <p>{{ product.description }}</p>
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                    <div class="row form_row">
                        {% csrf_token %}
                        {{ cart_product_form }}
                        <h5>{{product.measurement}}</h5>
                    </div>
                    <input type="submit" value="Savatchaga qo'shish" class="btn btn-outline-danger">
                </form>              
            </div>
        </div>
    </section>

</main>
{% endblock %}

shop/templates/shop/product/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Uzrozgor{% endblock title %}

{% block content %}
<main>


    <div class="container-fluid">
        <section class="header_slider">
            <div class="owl-carousel slide3 owl-theme">
                <div class="item"><img src="{% static 'img/banner.jpg' %}" alt=""></div>
                <div class="item"><img src="{% static 'img/banner.jpg' %}" alt=""></div>
                <div class="item"><img src="{% static 'img/banner.jpg' %}" alt=""></div>
            </div>
        </section>
    </div>


    <section class="category">

        <div class="container-fluid">

            <div class="swiper-container swiper1">

                <div class="swiper-wrapper">
                    {% for category in category_list %}
                    <div class="swiper-slide">
                        <a class="category_name" href="{{ category.get_absolute_url }}">
                            <img src="{% if category.cover %}{{category.cover}}{% endif %}" alt="">
                            <h4>{{category.name}}</h4>
                        </a>
                    </div>
                    {% endfor %}
                </div>
                <!-- If we need pagination -->
                <!-- <div class="swiper-pagination"></div> -->

                <!-- If we need navigation buttons -->
                <div class="swiper-button-prev"><img src="img/left-arrow.png" alt=""></div>
                <div class="swiper-button-next"><img src="img/right-arrow.png" alt=""></div>

                <!-- If we need scrollbar -->
                <!-- <div class="swiper-scrollbar"></div> -->
            </div>

        </div>



    </section>


    <!-- <section class="new">
            <div class="container">
                <h3>Новые товары :</h3>
                <div class="owl-carousel slide2 owl-theme">
                    {% for product in product_list %}
                    {% if product.was_added_recently %}
                    <div class="item">
                        <img src="{{product.image.url}}" alt="">
                        <p>{{product.name}}</p>
                        <h4>{{product.price}} сум</h4>
                        <div class="item_buttons">
                            <a href="{{ product.get_absolute_url }}">Посмотреть</a>
                            
                        </div>
                     </div>
                     {% endif %}
                     {% endfor %}
                     
                </div>
            </div>
        </section> -->


    {% for category in category_list %}
    <section class="new">
        <div class="container-fluid">
            <h3>{{category.name}}:</h3>
            <div class="swiper-container">
                <!-- Additional required wrapper -->
                <div class="swiper-wrapper swiper1">
                    <!-- Slides -->
                    {% for product in category.products.all %}
                    <div class="swiper-slide">
                        <div class="slide">
                            <div class="item">
                                <img src="{% if product.image %}{{product.image}}{% endif %}" alt="">
                                <p>{{product.name}}</p>
                                <h4>{{ product.price }} so'm</h4>
                                <div class="item_buttons">
                                    <a href="{{ product.get_absolute_url }}">Batafsil</a>
                                </div>
                                <div class="dropdown_div">
                                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                                        {% csrf_token %}
                                        {{ cart_product_form }}
                                        <select name="quantity" class="form-control" id="id_quantity">
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                            <option value="6">6</option>
                                            <option value="7">7</option>
                                            <option value="8">8</option>
                                            <option value="9">9</option>
                                            <option value="10">10</option>
                                        </select>
                                        <h5>{{product.measurement}}</h5>
                                        <input type="hidden" name="update" value="False" id="id_update">
                                        <input type="submit" value="xaridga qo'shish">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!-- If we need pagination -->

                <!-- If we need navigation buttons -->
                <div class="swiper-button-prev"><img src="{% static 'img/left-arrow.png' %}" alt=""></div>
                <div class="swiper-button-next"><img src="{% static 'img/right-arrow.png' %}" alt=""></div>

                <!-- If we need scrollbar -->
                <div class="swiper-scrollbar"></div>
            </div>
        </div>
    </section>
    {% endfor %}
</main>
{% endblock content %}

shop/templates/shop/product/search_results.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Search{% endblock title %}

{% block content %}
<main>
    <section class="find_text">
        <h1>Qidiruv natijalari</h1>
    </section>
    <section class="poisk2">



        <div class="container-fluid">

            <div class="poisk_row">

                {% for product in product_list %}
                <div class="item col-lg-3">
                    <img src="{% if product.image %}{{product.image}}{% endif %}" alt="">
                    <p>{{product.name}}</p>
                    <h4>{{product.price}} so'm</h4>
                    <div class="item_buttons">
                        <a href="{{product.get_absolute_url}}">Batafsil</a>
                    </div>
                    <div class="dropdown_div">
                        <form action="{% url "cart:cart_add" product.id %}" method="post">
                            {% csrf_token %}
                            {{ cart_product_form }}
                            <select name="quantity" class="form-control" id="id_quantity">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                            </select>
                            <h5>{{product.measurement}}</h5>
                            <input type="hidden" name="update" value="False" id="id_update">
                            <input type="submit" value="xaridga qo'shish">
                        </form>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</main>

{% endblock content %}